APP:
  NAME: gin_weibo
  RUNMODE: debug # 模式: debug, release, test
  Addr: :8888 # 端口
  URL: http://localhost:8888 # 网站 url，内部跳转时会用到该项
  KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
  ENABLE_CSRF: true # 是否开启 csrf

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: gin_weibo
  USERNAME: wutong
  PASSWORD: secret

MAIL:
  MAIL_DRIVER: smtp # smtp or log (smtp: 使用支持 ESMTP 的 SMTP 服务器发送邮件，log: 适用于调试，会将邮件内容写入 log 中)
  MAIL_HOST: smtp.mailtrap.io # 邮箱的 SMTP 服务器地址
  MAIL_PORT: 2525 # 邮箱的 SMTP 服务器端口
  MAIL_USERNAME:
  MAIL_PASSWORD: # 授权码或密码
  MAIL_FROM_NAME: gin_weibo # 用来作为邮件的发送者名称
